### ISSUE TITLE
Résultats bizarre de script F-score

### ISSUE THREAD

**Issue by NikaAb** [julibinho/cloneCluster#1]
Hey @LisaC1234 and @QuentinStr !

Il y avait un problème de gestion des "retour à la ligne" dans le scripte, le script ne contait pas les dernières séquences de chaque cluster dans le fichier résultat. Grace à vous, on le sait maintenant ´･ᴗ･`

Voici les résultats :
Pre = 0.90, Rec =  0.61, F-score = 0.73

Il faut savoir que dans le fichier res.txt on a 940 seq et le fichier d'entré contient 956 seq. 
Je ne sais pas les détails sur les séquences qui n'ont pas été regroupé par l'algo (et je suis curieuse d'en savoir plus) mais chaque séquence qui n'est pas dans le fichier de sortie, est considérée comme un singleton (un cluster qui contient un seul objet) car il n'a pas été regroupé avec d'autres séquences, cela pourrait justifier un recall un peu plus bas que prévu.

**Comment by julibinho** [comment]
Merci Nika, les resultats sont pas mal :-)
@NikaAb, est-ce que ce bug affect les resultats de FaIR et les autres outils?

**Comment by NikaAb** [comment]
@julibinho , non, le format de fichier res.txt était différent au niveau des retours à la ligne, on comptait déjà toutes les sequences dans les autres fichiers de sorties.
