### ISSUE TITLE
Meeting 01/04

### ISSUE THREAD

**Issue by julibinho** [julibinho/cloneCluster#5]
Hi,

Did we schedule a meeting for today?
I don't remember, I didn't note anything.

Best

**Comment by NikaAb** [comment]
Hey!
I am a little confused as well (・・。)ゞ
Let's meet tomorrow (Thursday 2/04/2020) at 15h30, is it OK for you @LisaC1234 @QuentinStr ?

**Comment by QuentinStr** [comment]
C'est ok pour Lisa et moi-même demain à 15h30.

**Comment by julibinho** [comment]
Bonjour,

Voici le code pour le meeting 3969651689
à tt

**Comment by julibinho** [comment]
Bonjour,
c'est touours le meme code 3969651689
