### ISSUE TITLE
Organisation Repository

### ISSUE THREAD

**Issue by julibinho** [julibinho/cloneCluster#7]
Bonjour,

j'ai finit d'organiser le répertoire. 

algoCluster => les codes des algorithmes, PAS de fichiers de resultats.
data => Les données artificiel et reel
docs/ => papers, tutorials, descriptions, votre rapport quand il sera pret
evaluation/  =>  scripts pour evaluer les algorithmes, **ca sera bien d'avoir un readMe avec des exemples de comment lancer ces scripts**.
result/ => J'ai ajouté deux repertoires, **Analyses** pour mettre les analyses de resultats, comme pourquoi les recall sont tres bas, et aussi de probleme qu'on trouve dans les donnees. Le repertoire comparisons pour comparer les algos.
simulators/immuneSIM => pour les simulations

### Qu'est-ce que reste à faire.

Dans algoCluster il y a deux dossier nommé TestBench et Tool, renomer avec un nom plus significative. Netoyer si possible, il me semble que il ya bp de fichiers qui ne sont pas utiliser.

Dans result/comparisons/ vous trouver tous les résultats, il faut créer un fichier excel éditable et mettre tous les résultats ensemble, vous pouvez créer deux sheets une pour artificial et autre pour real results.

Je vous conseille d'utiliser la version web et upload seulement les fichiers nécessaires, après avoir bien tester votre code.

J'ai trouvé beaucoup de fichiers de teste ou d'essaie. Je vous conseille de

**Comment by LisaChabrier** [comment]
Bonjour, 

Tool est renomé et Test_bench est supprimé, le tableau excel est créé (mais pas encore entièrement complété).
